# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: CHK768
description: >- # this means to ignore newlines until "baseurl:"
  The personal site of Kyle Chen.
baseurl: "/bay" # the subpath of the site
url: "https://chk768.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: chenhuankang@outlook.com
    - type: wechat
      value: CHK
      link: "#"
  follow:
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/kylechen768
    - type: github
      name: GitHub
      link: http://github.com/CHK768
    - type: dune
      name: Dune
      link: https://dune.com/ethereal768

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
